# Generated by Django 4.1.7 on 2023-02-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='positive',
        ),
        migrations.AddField(
            model_name='review',
            name='positive',
            field=models.BooleanField(default=True),
        ),
    ]
